{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "itsaplan.fullname" . }}-minio
  labels:
    {{- include "itsaplan.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "itsaplan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
